Repository pester/Pester, pull requests merged in 2023-05, with the labels that each got.

#2336 Fix module import performance regression
  src/Main.ps1
  src/functions/Pester.SessionState.Mock.ps1
  src/functions/assertions/Be.ps1
  src/functions/assertions/BeGreaterThan.ps1
  src/functions/assertions/BeIn.ps1
  src/functions/assertions/BeLessThan.ps1
  src/functions/assertions/BeLike.ps1
  src/functions/assertions/BeLikeExactly.ps1
  src/functions/assertions/BeNullOrEmpty.ps1
  src/functions/assertions/BeOfType.ps1
  src/functions/assertions/BeTrueOrFalse.ps1
  src/functions/assertions/Contain.ps1
  src/functions/assertions/Exist.ps1
  src/functions/assertions/FileContentMatch.ps1
  src/functions/assertions/FileContentMatchExactly.ps1
  src/functions/assertions/FileContentMatchMultiline.ps1
  src/functions/assertions/FileContentMatchMultilineExactly.ps1
  src/functions/assertions/HaveCount.ps1
  src/functions/assertions/HaveParameter.ps1
  src/functions/assertions/Match.ps1
  src/functions/assertions/MatchExactly.ps1
  src/functions/assertions/PesterThrow.ps1
  tst/Help.Tests.ps1
  tst/functions/Add-ShouldOperator.ts.ps1
Labels: Bug

#2208 Add support for NUnit3 XML-reports
  build.ps1
  src/Module.ps1
  src/Pester.RSpec.ps1
  src/Pester.Runtime.ps1
  src/csharp/Pester/TestResultConfiguration.cs
  src/functions/TestResults.NUnit3.ps1
  src/functions/TestResults.ps1
  src/schemas/NUnit3/TestDefinitions.xsd
  src/schemas/NUnit3/TestFilterDefinitions.xsd
  src/schemas/NUnit3/TestResult.xsd
  tst/Pester.RSpec.Nunit3.TestResults.ts.ps1
Labels: Feature

#2273 Add -InParameterSet in Should -HaveParameter
  src/functions/assertions/HaveParameter.ps1
  tst/functions/assertions/HaveParameter.Tests.ps1
Labels: Feature

#2341 Reattach TestDrive and TestRegistry after running inner Invoke-Pester
  src/Main.ps1
  src/functions/Environment.ps1
  src/functions/TestDrive.ps1
  src/functions/TestRegistry.ps1
  tst/functions/TestDrive.Tests.ps1
  tst/functions/TestRegistry.Tests.ps1
Labels: Feature

#2346 Add Run.Exit option clarification
  src/csharp/Pester/RunConfiguration.cs
Labels: Documentation
